### ISSUE TITLE
zero last click

### ISSUE THREAD

**Issue by ArgusRho** [ArgusRho/flipcard-randomizer-js#1]
if the last one clicked is zero then we wont win because it doesnt check win condition afterwards. fixed in the site version.

**Comment by TeoTeoTeo1204** [comment]
assign this issue to me

**Comment by TeoTeoTeo1204** [comment]
hey @ArgusRho , i have finished this issue. However, I found that the image is quite oversize now, I would like to make the image smaller and the font bigger, and customize the start and reset buttons. Do you need that?

**Comment by ArgusRho** [comment]
> hey @ArgusRho , i have finished this issue. However, I found that the image is quite oversize now, I would like to make the image smaller and the font bigger, and customize the start and reset buttons. Do you need that?

you are free to do anything you want with the code! you can also use the code for your needs :)
